name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
   steps:
    name: Lint Action
    uses: wearerequired/lint-action@v2.3.0
    
            
